CREATE TABLE podcast (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  slug VARCHAR(10) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(500) NOT NULL,
  purchased TINYINT(1) NOT NULL DEFAULT 0,
  purchased_dt DATETIME NULL
) ENGINE=InnoDB;